<a href="https://colab.research.google.com/github/1ShahidBashir/numpy/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#creating numpy/ n-d arrays
import numpy as np

In [4]:
arr=[1,2,3,4,5]
arr1=np.array(arr)
#one of the ways to create a numpy array

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
#2d array (n-d) as numpy array
arr2=np.array([[1,2,3,4],[9,8,5,6]])
arr2

array([[1, 2, 3, 4],
       [9, 8, 5, 6]])

In [8]:
#looks like a matrix

In [9]:
#initialising array with passing shape in a tuple
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#same with ones
arr4=np.ones((4,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#another way by identity matrix
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
#another way by a range
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr7=np.arange(5,16,2)    #for loop range
arr7

array([ 5,  7,  9, 11, 13, 15])

In [14]:
#using linspace we will get float array with same distances between the
# elements

arr8=np.linspace(10,20,10)  #between 10 to 20 equal spaces 10 floats
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
#another
arr9=arr8.copy()
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [16]:
#shape of array
arr1.shape

(5,)

In [17]:
arr2.shape

(2, 4)

In [18]:
arr10=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
arr10.shape
# 2 arrays of shape 2 rows and 2 colums

(2, 2, 2)

In [20]:
arr10.ndim
# finding dimesions of a matrix/array

3

In [21]:
arr2.ndim

2

In [22]:
arr1

array([1, 2, 3, 4, 5])

In [23]:
arr1.size
#size= no of items

5

In [24]:
arr10.size

8

In [25]:
arr1.itemsize
#shows size of each item (bytes)

8

In [26]:
arr1.dtype

dtype('int64')

In [27]:
#changing data type
arr10.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [29]:
#advantages of arrays over lists
#size
lista=range(100)
arr11=np.arange(100)

In [30]:
import sys

In [32]:
#since 87 is a member of list then
#total list size= member*len of list
print(sys.getsizeof(87)*len(lista))

2800


In [34]:
print(arr11.itemsize*arr11.size)

800


In [36]:
#arrays are faster than lists
# here x,y are lists
import time
x=range(100000)
y=range(100000,200000) #from 1 lk to 2 lk
start_time=time.time() #time method in time module stores current time
c=[(x+y) for x,y in zip(x,y)] #adding all correspoding elements
print(time.time()-start_time) #will give execution time for upper code

0.014926433563232422


In [37]:
a=np.arange(100000)
b=np.arange(100000,200000)
star=time.time()
c=a+b
print(time.time()-star)

0.00493311882019043


In [38]:
#see difference in time of execution for same operations

In [39]:
# see above the simplicity of syntax